AN-101 Update Travis and phpunit test rules

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,61 +1,126 @@
+# Tell Travis to use new container-based infrastructure
 sudo: false
 
+# Declare project language.
+# @link http://about.travis-ci.org/docs/user/languages/php/
 language: php
 
-notifications:
-  email:
-    on_success: never
-    on_failure: change
-
+# Specify when Travis should build.
 branches:
   only:
     - master
 
+# Git clone depth.
+git:
+  depth: 1
+
 matrix:
   include:
     - php: 5.3
-      env: WP_VERSION=latest
+      env: WP_VERSION=latest PHP_LINT=1
       dist: precise
     - php: 5.6
-      env: WP_VERSION=latest
+      env: WP_VERSION=latest PHP_LINT=1
     - php: 7.0
-      env: WP_VERSION=latest
+      env: WP_VERSION=latest PHP_LINT=1
     - php: 7.1
-      env: WP_VERSION=latest
+      env: WP_VERSION=latest PHP_LINT=1
     - php: 7.2
-      env: WP_VERSION=latest
-    - php: 5.6
-      env: WP_VERSION=nightly
-    # - php: 5.6
-    #   env: WP_TRAVISCI=phpcs
+      env: WP_VERSION=latest PHP_LINT=1 WP_PHPCS=1
   fast_finish: true
 
+# Use this to prepare the system to install prerequisites or dependencies.
+# e.g. sudo apt-get update.
+# Failures in this section will result in build status 'errored'.
+before_install:
+
+# Use this to prepare your build for testing.
+# e.g. copy database configurations, environment variables, etc.
+# Failures in this section will result in build status 'errored'.
 before_script:
+  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
+  - phpenv config-rm xdebug.ini || echo "Xdebug not available"
+
   - export PATH="$HOME/.composer/vendor/bin:$PATH"
+
+  # Couple the PHPUnit version to the PHP version.
   - |
-      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
-        composer global require "phpunit/phpunit=5.7.*"
-      else
+    case "$TRAVIS_PHP_VERSION" in
+      7.2|7.1|7.0)
+        echo "Using PHPUnit 6.1"
+        composer global require "phpunit/phpunit=6.1.*"
+        ;;
+      5.6|5.3)
+        echo "Using PHPUnit 4.8"
         composer global require "phpunit/phpunit=4.8.*"
-      fi
-  - composer install
+        ;;
+      *)
+        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
+        exit 1
+        ;;
+    esac
+
+  - og_dir="$(pwd)"
+
+  # Set up WordPress installation.
+  - export WP_DEVELOP_DIR=/tmp/wordpress
+  - export WP_TESTS_DIR=${WP_DEVELOP_DIR}/tests/phpunit
+  - export WP_CORE_DIR=${WP_DEVELOP_DIR}/src/
+  - mkdir -p $WP_DEVELOP_DIR
+
+  # Use the Git mirror of WordPress.
+  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
+
+  # Set up WordPress configuration.
+  - cd $WP_DEVELOP_DIR
+  - echo $WP_DEVELOP_DIR
+  - cp wp-tests-config-sample.php wp-tests-config.php
+  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
+  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
+  - sed -i "s/yourpasswordhere//" wp-tests-config.php
+  - echo "define( 'JETPACK_DEV_DEBUG', true );" >> wp-tests-config.php
+  - cat wp-tests-config.php
+
+  # Create WordPress database.
+  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
+
+  # Set up phpcs
   - |
-    if [[ ! -z "$WP_VERSION" ]] ; then
-      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
-    fi
-  - |
-    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
-      npm install
+    if [[ "$WP_PHPCS" == "1" ]]; then
+      cd $og_dir
+      composer install
+      export PATH=$PATH:${og_dir}/vendor/bin/
+      # After CodeSniffer install you should refresh your path.
+      phpenv rehash
     fi
 
+  # For debugging.
+  - which phpunit
+  - phpunit --version
+  - pwd
+
+# Run test script commands.
+# Default is specific to project language.
+# All commands must exit with code 0 on success. Anything else is considered failure.
 script:
-  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
-  - |
-    if [[ ! -z "$WP_VERSION" ]] ; then
-      phpunit
-      phpunit -c multisite.xml
-    fi
-  - |
-    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
-      grunt phpcs
-    fi
+    # Search for PHP syntax errors.
+    #
+    # Only need to run this once per PHP version.
+    - if [[ "$PHP_LINT" == "1" ]]; then find . -type "f" -iname "*.php" | xargs -L "1" php -l; fi
+
+    # WordPress Coding Standards.
+    #
+    # These are the same across PHP and WordPress, so we need to run them only once.
+    #
+    # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
+    # @link http://pear.php.net/package/PHP_CodeSniffer/
+    - if [[ "$WP_PHPCS" == "1" ]]; then phpcs -v; fi
+
+    # Test the theme's unit tests
+    - phpunit
+    - phpunit -c multisite.xml
+
+# Receive notifications for build results.
+# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
+notifications:
+    email: false
