AN-101 Revert .travis.yml to master version to debug failure

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -27,6 +27,8 @@ matrix:
     - php: 7.2
       env: WP_VERSION=nightly
   fast_finish: true
+  allow_failures:
+    - env: WP_VERSION=nightly
 
 # Use this to prepare your build for testing.
 # e.g. copy database configurations, environment variables, etc.
@@ -53,7 +55,43 @@ before_script:
   - og_dir="$(pwd)"
 
   # Set up WordPress installation.
-  bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
+  - export WP_DEVELOP_DIR=/tmp/wordpress
+  - export WP_TESTS_DIR=${WP_DEVELOP_DIR}/tests/phpunit
+  - export WP_CORE_DIR=${WP_DEVELOP_DIR}/src/
+  - mkdir -p $WP_DEVELOP_DIR
+
+  # Use the Git mirror of WordPress.
+  - |
+    case "$WP_VERSION" in
+      latest)
+        curl -s http://api.wordpress.org/core/version-check/1.7/ > /tmp/wp-latest.json
+        grep '[0-9]+\.[0-9]+(\.[0-9]+)?' /tmp/wp-latest.json
+        LATEST_VERSION=$(grep -o '"version":"[^"]*' /tmp/wp-latest.json | sed 's/"version":"//')
+        if [[ -z "$LATEST_VERSION" ]]; then
+          echo "Latest WordPress version could not be found."
+          exit 1
+        fi
+        git clone --depth=1 --branch="$LATEST_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
+        ;;
+      nightly)
+        git clone --depth=1 --branch="master" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
+        ;;
+      *)
+        git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
+        ;;
+    esac
+
+  # Set up WordPress configuration.
+  - cd $WP_DEVELOP_DIR
+  - echo $WP_DEVELOP_DIR
+  - cp wp-tests-config-sample.php wp-tests-config.php
+  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
+  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
+  - sed -i "s/yourpasswordhere//" wp-tests-config.php
+  - cat wp-tests-config.php
+
+  # Create WordPress database.
+  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
 
   # Install Composer dependencies.
   - cd $og_dir
